// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetCloudPlatform sets provided value as "cloud.platform" attribute.
func (rb *ResourceBuilder) SetCloudPlatform(val string) {
	if rb.config.CloudPlatform.Enabled {
		rb.res.Attributes().PutStr("cloud.platform", val)
	}
}

// SetCloudProvider sets provided value as "cloud.provider" attribute.
func (rb *ResourceBuilder) SetCloudProvider(val string) {
	if rb.config.CloudProvider.Enabled {
		rb.res.Attributes().PutStr("cloud.provider", val)
	}
}

// SetCloudRegion sets provided value as "cloud.region" attribute.
func (rb *ResourceBuilder) SetCloudRegion(val string) {
	if rb.config.CloudRegion.Enabled {
		rb.res.Attributes().PutStr("cloud.region", val)
	}
}

// SetHostID sets provided value as "host.id" attribute.
func (rb *ResourceBuilder) SetHostID(val string) {
	if rb.config.HostID.Enabled {
		rb.res.Attributes().PutStr("host.id", val)
	}
}

// SetHostName sets provided value as "host.name" attribute.
func (rb *ResourceBuilder) SetHostName(val string) {
	if rb.config.HostName.Enabled {
		rb.res.Attributes().PutStr("host.name", val)
	}
}

// SetOracleCloudInfrastructureInstanceAvailabilityDomain sets provided value as "oracle_cloud_infrastructure.instance.availability_domain" attribute.
func (rb *ResourceBuilder) SetOracleCloudInfrastructureInstanceAvailabilityDomain(val string) {
	if rb.config.OracleCloudInfrastructureInstanceAvailabilityDomain.Enabled {
		rb.res.Attributes().PutStr("oracle_cloud_infrastructure.instance.availability_domain", val)
	}
}

// SetOracleCloudInfrastructureInstanceDisplayName sets provided value as "oracle_cloud_infrastructure.instance.display_name" attribute.
func (rb *ResourceBuilder) SetOracleCloudInfrastructureInstanceDisplayName(val string) {
	if rb.config.OracleCloudInfrastructureInstanceDisplayName.Enabled {
		rb.res.Attributes().PutStr("oracle_cloud_infrastructure.instance.display_name", val)
	}
}

// SetOracleCloudInfrastructureInstanceID sets provided value as "oracle_cloud_infrastructure.instance.id" attribute.
func (rb *ResourceBuilder) SetOracleCloudInfrastructureInstanceID(val string) {
	if rb.config.OracleCloudInfrastructureInstanceID.Enabled {
		rb.res.Attributes().PutStr("oracle_cloud_infrastructure.instance.id", val)
	}
}

// SetOracleCloudInfrastructureInstanceShape sets provided value as "oracle_cloud_infrastructure.instance.shape" attribute.
func (rb *ResourceBuilder) SetOracleCloudInfrastructureInstanceShape(val string) {
	if rb.config.OracleCloudInfrastructureInstanceShape.Enabled {
		rb.res.Attributes().PutStr("oracle_cloud_infrastructure.instance.shape", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
