// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for resourcedetectionprocessor/oracle_cloud_infrastructure resource attributes.
type ResourceAttributesConfig struct {
	CloudPlatform                                       ResourceAttributeConfig `mapstructure:"cloud.platform"`
	CloudProvider                                       ResourceAttributeConfig `mapstructure:"cloud.provider"`
	CloudRegion                                         ResourceAttributeConfig `mapstructure:"cloud.region"`
	HostID                                              ResourceAttributeConfig `mapstructure:"host.id"`
	HostName                                            ResourceAttributeConfig `mapstructure:"host.name"`
	OracleCloudInfrastructureInstanceAvailabilityDomain ResourceAttributeConfig `mapstructure:"oracle_cloud_infrastructure.instance.availability_domain"`
	OracleCloudInfrastructureInstanceDisplayName        ResourceAttributeConfig `mapstructure:"oracle_cloud_infrastructure.instance.display_name"`
	OracleCloudInfrastructureInstanceID                 ResourceAttributeConfig `mapstructure:"oracle_cloud_infrastructure.instance.id"`
	OracleCloudInfrastructureInstanceShape              ResourceAttributeConfig `mapstructure:"oracle_cloud_infrastructure.instance.shape"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		CloudPlatform: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudProvider: ResourceAttributeConfig{
			Enabled: true,
		},
		CloudRegion: ResourceAttributeConfig{
			Enabled: true,
		},
		HostID: ResourceAttributeConfig{
			Enabled: true,
		},
		HostName: ResourceAttributeConfig{
			Enabled: true,
		},
		OracleCloudInfrastructureInstanceAvailabilityDomain: ResourceAttributeConfig{
			Enabled: true,
		},
		OracleCloudInfrastructureInstanceDisplayName: ResourceAttributeConfig{
			Enabled: true,
		},
		OracleCloudInfrastructureInstanceID: ResourceAttributeConfig{
			Enabled: true,
		},
		OracleCloudInfrastructureInstanceShape: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}
